### PR TITLE
add clickaway directive to games-panel

### PR DESCRIPTION
**Pull request by irina060981**
Add an ability to close game panel with clickaway directive (the same as for components)

### CODE REVIEW

**Comment by irina060981** [comment]
@kirlat , I don't quitely understand your suggestion - do you suggest to modify the clickaway directive as quitely undependent module with some parameters (we need to identify ignore html blocks like alpheios-popup, alpheios-panel and for my case alpheios-games).
And then exclude it from components and inflection-games and use at as a separate repo published to npm?
It sounds as independent project :)

**Comment by kirlat** [comment]
@irina060981, I just noticed that vue-clickaway is already available as an npm package: https://www.npmjs.com/package/vue-clickaway. So maybe we can just include `vue-clickaway` to a list of our dev dependencies, import, and use it. What do you think?

**Comment by kirlat** [comment]
Oh, I did not realize that our file was modified. Then, of course, using `vue-clickaway` npm package is not an option. But I like your idea (if I understand it correctly) to have one version of a directive file in our components repo and use it everywhere we need this functionality. This will follow DRY principle. What do you think? Is it possible to do? @balmas, what's your opinion on this?

**Comment by irina060981** [comment]
No, I didn't do this way - because there is another way to attach modules.

alpheios-inflection-games  are imported to alpheios-components
so it is independent from its structure and refactoring.

If I will import clickway directive there will be a link
alpheios-components <-> alpheios-inflection-games

it seems to me that it is not a correct linking between modules.

I think it is a better way to create some external library for all repos that used some common vue-tools and technique (components, games, lexical-tests and so on) and avoid to import a big and interactive alpheios-components.

**Comment by irina060981** [comment]
I have created it separately and made efforts to make it as much independent as it could (you could see that it has very less specific code in ui-controller.js of alpheios-components), because it was defined this way in the Bridget's task. 
If I understood it right it should be easily attached to something else in future :)

**Comment by kirlat** [comment]
If we need to have games independent, then they should probably be not included by components. They should be included at the final assembly point: in an end application that will use them (PWA, webextension, etc.).

I've checked components code and I've noticed that `GamesController` is used within a UI contorller. Probably in the future we should make it more flexible so that GamesController be somehow injected into a UI controller at the final assembly point or maybe subscribe to UI controller notifications (as about language change) and UI controller would stay truly universal. This will allow to untangle those dependencies. Something to think about during refactoring, probably.

**Comment by balmas** [comment]
This is all a good conversation :-)

Yes I think it is too soon to optimize exactly how and where the inflection-games live and their exact interaction with the other code. I liked @irina060981 's approach because it is very easy to add or remove the feature, e.g. in the embedded library without having any impact on any of the other functionality. This makes it easy to test as a prototype but it's quite possible that in the future we need it to be more interactive with other pieces of the interface too.

I agree with @kirlat  that embedding the GamesController within UIController is not ideal for the long run, but don't want to worry too much about the best way right now. This should all feed into refactoring thoughts though.

**Pull request merged**
